[theme]
base = "light"
primaryColor = "#4338CA"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0A0A0A"
font = "sans serif"

[server]
headless = true
runOnSave = true
fileWatcherType = "auto"
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
